/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package canelaSeca;

import actions.GetSetters;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author morok
 */
public class TresOitao extends javax.swing.JFrame implements AckGun  {

    /**
     * Creates new form TreisOitao
     */
    public TresOitao() {
        initComponents();
        lblDisarmed.setVisible(true);
        lblBang.setVisible(false);
        lblgunArmed.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblgunArmed = new javax.swing.JLabel();
        lblDisarmed = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblBang = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblScreenAmm = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(237, 48, 22));
        setLocation(new java.awt.Point(500, 100));
        setMinimumSize(new java.awt.Dimension(820, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("/home/morok/Desktop/projects/arms/oie.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 20, 20));

        lblgunArmed.setIcon(new javax.swing.ImageIcon("/home/morok/Downloads/revolver-3024894-2514593.png")); // NOI18N
        lblgunArmed.setText("iuyu");
        getContentPane().add(lblgunArmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 240, 120));

        lblDisarmed.setIcon(new javax.swing.ImageIcon("/home/morok/Desktop/projects/arms/revolver-3024894-2514593.png")); // NOI18N
        getContentPane().add(lblDisarmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 234, 120));

        jButton2.setText("Pull hammer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, 20));

        lblBang.setIcon(new javax.swing.ImageIcon("/home/morok/Desktop/projects/arms/bang.png")); // NOI18N
        getContentPane().add(lblBang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, 80));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        jLabel4.setText("Ammunitions:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        lblScreenAmm.setFont(new java.awt.Font("Noto Sans Mono", 1, 18)); // NOI18N
        lblScreenAmm.setForeground(new java.awt.Color(255, 114, 0));
        getContentPane().add(lblScreenAmm, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 30, 20));

        jButton3.setText("Reload");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(b1.getPullTregger() == true){
            
            this.fire();
            
        }else{
            
            lblDisarmed.setVisible(true);
            lblgunArmed.setVisible(false);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        this.downBackHammer();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.reload();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TresOitao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TresOitao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TresOitao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TresOitao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TresOitao().setVisible(true);
            }
        });
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public JLabel getjLabel1() {
        return lblBang;
    }

    public JLabel getjLabel2() {
        return lblDisarmed;
    }

    public JLabel getjLabel3() {
        return lblgunArmed;
    }
    
    public JLabel getLblScreenAmm(){
        return lblScreenAmm;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBang;
    private javax.swing.JLabel lblDisarmed;
    private javax.swing.JLabel lblScreenAmm;
    private javax.swing.JLabel lblgunArmed;
    // End of variables declaration//GEN-END:variables

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.lblBang = jLabel1;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.lblDisarmed = jLabel2;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.lblgunArmed = jLabel3;
    }
    
 

    public void setLblScreenAmm() {
        this.lblScreenAmm = lblScreenAmm;
    }

    @Override
    public void reload() {
        
        b1.setAmmunitions(5);
        lblScreenAmm.setText(Integer.toString(b1.getAmmunitions()));
    }
    ///////////////
    GetSetters b1 = new GetSetters();
    ///------------------------------------------------------------------------
    @Override
    public void downBackHammer() {
        
        lblBang.setVisible(false);
        GetSetters a1 = new GetSetters();
        GetSetters v1 = new GetSetters();
        
        if(v1.getShot() == true){
            
            lblgunArmed.setVisible(false);
            lblDisarmed.setVisible(true);
            a1.setPullTregger(true);
        }
        else if(v1.getShot() == false){
            lblDisarmed.setVisible(false);
            lblgunArmed.setVisible(true);
            b1.setPullTregger(true);
           
            
        }else
        {
            lblDisarmed.setVisible(true);
            lblgunArmed.setVisible(false);
        }
        
        
    }

    @Override
    public void fire() {
      
        GetSetters m2 = new GetSetters();
        
        if( b1.getPullTregger() == true && b1.getAmmunitions() > 0){
            for(int cont = 0; cont < m2.getFire(); cont++){
                lblDisarmed.setVisible(true);
                lblBang.setVisible(true);
                lblgunArmed.setVisible(false);
                
                b1.setAmmunitions(b1.getAmmunitions() - m2.getFire());
                lblScreenAmm.setText(Integer.toString(b1.getAmmunitions()));
                b1.setPullTregger(false);
            }
            
        }else{
            lblDisarmed.setVisible(true);
            lblgunArmed.setVisible(false);
            b1.setPullTregger(false);
        }
        
    }

  
    
    
}
